version: '3'

services:
  web:
    build: .
    command: 'web'
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - default
      - authentication

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: 'authentication'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:

networks:
  authentication:
    external: true